FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]Microsoft apply reasonable efforts to on the VSTS Organization. If It is confirmed that this problem is caused by Microsoft Team Services Product, and there is a solution or a feasible workaround, we will provide an action plan to address it. If we find that there are clearly different issues or different products, we may have to separate the work in different support cases. In case we identify the behavior is generated by other components different than our Microsoft Team Services Product, we will provide recommendations, but you will have to contact the provider to sync with them the solution. Once we provide this information, we will consider the Solution Delivered and the Case as Closed.